INSERT INTO DOCUMENTS(id, state)
VALUES (1, 'DRAFT');
INSERT INTO DOCUMENTS(id, state)
VALUES (2, 'UNDER_MEDIATION');
INSERT INTO DOCUMENTS(id, state)
VALUES (3, 'WAITING_FOR_PUBLIC_DISCLOSURE');
INSERT INTO DOCUMENTS(id, state)
VALUES (4, 'PUBLIC_DISCLOSURE');
