DROP TABLE IF EXISTS DOCUMENTS;
DROP TABLE IF EXISTS DOCUMENTS_STATE_HISTORY;
CREATE TABLE DOCUMENTS
(
    id    INTEGER NOT NULL,
    state VARCHAR(255) NULL DEFAULT 'DRAFT',
    PRIMARY KEY (id)
);

CREATE TABLE DOCUMENTS_STATE_HISTORY
(
    id IDENTITY NOT NULL PRIMARY KEY,
    document_id   INTEGER      NOT NULL,
    event         VARCHAR(255) NOT NULL,
    prev_state    VARCHAR(255) NULL DEFAULT 'DRAFT',
    changed_state VARCHAR(255) NOT NULL,
    triggered_at  TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP
);
